name: linda_wedding_ecommerce
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  auto_route: ^5.0.1
  build_runner: ^2.2.0
  connectivity_plus: ^2.3.7
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_rating_bar: ^4.0.1
  gradient_borders: ^0.2.0
  hive: ^2.2.3
  http: ^0.13.5
  kartal: ^2.4.3
  shimmer: ^2.0.0
  vexana: ^3.0.1

dev_dependencies:
  auto_route_generator: ^5.0.2
  hive_generator: ^1.1.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
