import '../../../features/product/model/product_model.dart';

class ApplicationConstants {
  static const langAssetPath = 'asset/lang';

  static final List<ProductModel> productOptions = <ProductModel>[
    ProductModel(
        id: 1,
        title: "Deneme1",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 2,
        title: "Deneme2",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 3,
        title: "Deneme3",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 4,
        title: "Deneme4",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 4,
        title: "Deneme4",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 4,
        title: "Deneme4",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 4,
        title: "Deneme4",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 4,
        title: "Deneme4",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 4,
        title: "Deneme4",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 4,
        title: "Deneme4",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 4,
        title: "Deneme4",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 4,
        title: "Deneme4",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 4,
        title: "Deneme4",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
    ProductModel(
        id: 4,
        title: "Deneme2",
        price: 150,
        description: "Deneme1 desc",
        category: "sss",
        image: "ssdsd",
        rating: Rating(count: 100, rate: 3)),
  ];
}
